const $=x=>document.getElementById(x), C=["Boissons","Produits frais","Fruits & légumes","Viandes & poissons","Épicerie & condiments","Hygiène","Maison","Autres"],K={p:"cv2p",m:"cv2m",e:"cv2e"},load=k=>{try{return JSON.parse(localStorage.getItem(k)||"[]")}catch{return[]}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v)),uid=()=>crypto.randomUUID?.()||Date.now()+""+Math.random(),esc=s=>{let d=document.createElement("div");d.textContent=s;return d.innerHTML};
let P=load(K.p),M=load(K.m),E=load(K.e),view="all",prep=null;const opts=s=>C.map(c=>`<option ${c===s?"selected":""}>${c}</option>`).join("");$("pc").innerHTML=opts();
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button,.page").forEach(x=>x.classList.remove("on"));b.classList.add("on");$(b.dataset.p).classList.add("on");render()});
function groups(a,fn){return C.map(c=>{let z=a.filter(x=>x.category===c);return z.length?`<div class="group"><h3>${c}</h3>${z.map(fn).join("")}</div>`:""}).join("")}
function rp(){let q=$("search").value.toLowerCase();let a=P.filter(p=>p.name.toLowerCase().includes(q));$("prods").innerHTML=groups(a,p=>`<div class="item"><div><b>${esc(p.name)}</b><div class="tags">${p.stock?'<span class="tag stock">En stock</span>':""}${p.buy?'<span class="tag buy">À acheter</span>':""}</div></div><div class="acts"><button class="${p.stock?"active":""}" onclick="stock('${p.id}')">🥫</button><button class="${p.buy?"active":""}" onclick="buy('${p.id}')">🛒</button><button onclick="delp('${p.id}')">×</button></div></div>`)}
window.stock=i=>{let p=P.find(x=>x.id===i);p.stock=!p.stock;save(K.p,P);render()};window.buy=i=>{let p=P.find(x=>x.id===i);p.buy=!p.buy;save(K.p,P);render()};window.delp=i=>{if(confirm("Supprimer ce produit ?")){P=P.filter(x=>x.id!==i);M.forEach(m=>m.ingredients=m.ingredients.filter(x=>x!==i));save(K.p,P);save(K.m,M);render()}};
$("pf").onsubmit=e=>{e.preventDefault();let n=$("pn").value.trim();if(!n)return;let p=P.find(x=>x.name.toLowerCase()===n.toLowerCase());if(p)p.category=$("pc").value;else P.push({id:uid(),name:n,category:$("pc").value,stock:false,buy:false});save(K.p,P);e.target.reset();$("pc").innerHTML=opts();render()};$("search").oninput=rp;
function rs(){let a=P.filter(p=>p.buy);$("shop").innerHTML=groups(a,p=>`<div class="card item"><div><b>${esc(p.name)}</b>${p.stock?'<div class="tags"><span class="tag stock">Déjà en stock</span></div>':""}</div><button class="soft" onclick="buy('${p.id}')">Retirer</button></div>`);$("shopEmpty").classList.toggle("hide",a.length>0);$("finish").classList.toggle("hide",!a.length)}
$("finish").onclick=()=>{if(confirm("Mettre tous ces achats en stock et vider la liste ?")){P.filter(p=>p.buy).forEach(p=>{p.buy=false;p.stock=true});save(K.p,P);render()}};
function ensure(n,c){let p=P.find(x=>x.name.toLowerCase()===n.toLowerCase());if(!p){p={id:uid(),name:n,category:c,stock:false,buy:false};P.push(p)}return p}
function ingrow(n="",c="Autres"){let d=document.createElement("div");d.className="ing";d.innerHTML=`<input value="${esc(n)}" placeholder="Ingrédient"><select>${opts(c)}</select><button type="button">×</button>`;d.querySelector("button").onclick=()=>d.remove();return d}
$("addIng").onclick=()=>$("ings").append(ingrow());$("newMeal").onclick=()=>openMeal();
window.openMeal=i=>{let m=M.find(x=>x.id===i);$("mf").reset();$("mid").value=m?.id||"";$("mn").value=m?.name||"";$("editTitle").textContent=m?"Modifier le plat":"Nouveau plat";$("ings").innerHTML="";(m?.ingredients||[""]).forEach(pid=>{let p=P.find(x=>x.id===pid);$("ings").append(ingrow(p?.name||"",p?.category||"Autres"))});$("editModal").classList.remove("hide")};
$("mf").onsubmit=e=>{e.preventDefault();let name=$("mn").value.trim(),ings=[...$("ings").children].map(r=>({n:r.querySelector("input").value.trim(),c:r.querySelector("select").value})).filter(x=>x.n).map(x=>ensure(x.n,x.c).id),m=M.find(x=>x.id===$("mid").value);if(m){m.name=name;m.ingredients=ings}else M.push({id:uid(),name,ingredients:ings,week:false});save(K.p,P);save(K.m,M);$("editModal").classList.add("hide");render()};
const missing=m=>m.ingredients.filter(i=>!P.find(p=>p.id===i)?.stock).length;
function rm(){let a=[...M];if(view==="week")a=a.filter(m=>m.week);if(view==="possible")a.sort((x,y)=>missing(x)-missing(y));$("mealList").innerHTML=a.map(m=>`<div class="card"><div class="item"><div><b>${esc(m.name)}</b><div class="meta">${m.ingredients.length} ingrédients · ${missing(m)?`<span class="miss">il manque ${missing(m)}</span>`:'<span class="ok">tout est disponible ✓</span>'}</div></div><button class="soft" onclick="openMeal('${m.id}')">Modifier</button></div><div class="mealBtns"><button class="${m.week?"week":""}" onclick="week('${m.id}')">📌 ${m.week?"Dans la semaine":"Ajouter à la semaine"}</button><button class="main" onclick="prepare('${m.id}')">🛒 Préparer les courses</button></div></div>`).join("");$("mealEmpty").classList.toggle("hide",a.length>0)}
window.week=i=>{let m=M.find(x=>x.id===i);m.week=!m.week;save(K.m,M);rm()};window.prepare=i=>{prep=M.find(x=>x.id===i);$("prepName").textContent=prep.name;$("prep").innerHTML=prep.ingredients.map(i=>{let p=P.find(x=>x.id===i);return p?`<div class="check"><input type="checkbox" data-id="${p.id}" ${p.stock?"":"checked"}><label>${esc(p.name)} ${p.stock?'<span class="tag stock">En stock</span>':""}</label></div>`:""}).join("");$("prepModal").classList.remove("hide")};
$("addToShop").onclick=()=>{$("prep").querySelectorAll("input:checked").forEach(c=>{let p=P.find(x=>x.id===c.dataset.id);if(p)p.buy=true});save(K.p,P);$("prepModal").classList.add("hide");render()}; // replaced below
document.querySelectorAll("[data-m]").forEach(b=>b.onclick=()=>{view=b.dataset.m;document.querySelectorAll("[data-m]").forEach(x=>x.classList.toggle("sel",x===b));rm()});
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>b.closest(".modal").classList.add("hide"));
const mk=()=>{let d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`},mname=k=>{let[y,m]=k.split("-");return new Date(+y,+m-1).toLocaleDateString("fr-FR",{month:"long",year:"numeric"})},eur=n=>new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(n);
function rb(){let a=E.filter(e=>e.month===mk()),s=a.reduce((n,e)=>n+e.amount,0);$("month").textContent=mname(mk());$("remain").textContent=eur(600-s);$("spent").textContent=eur(s);$("bar").style.width=Math.min(100,s/6)+"%";$("expenses").innerHTML=a.slice().reverse().map(e=>`<div class="item"><div><b>${esc(e.name)}</b><div class="meta">${new Date(e.date).toLocaleDateString("fr-FR")}</div></div><div><b>− ${eur(e.amount)}</b> <button onclick="dele('${e.id}')">×</button></div></div>`).join("")}
$("ef").onsubmit=e=>{e.preventDefault();let a=Number($("ea").value),n=$("en").value.trim();if(a>0&&n){E.push({id:uid(),amount:a,name:n,date:new Date().toISOString(),month:mk()});save(K.e,E);e.target.reset();rb()}};window.dele=i=>{E=E.filter(x=>x.id!==i);save(K.e,E);rb()};
function render(){rp();rs();rm();rb()}render();